---
title: "part-2"
author: "Jack Krebsbach"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup 
```{r}
require("knitr")
rm(list =ls())
gc()
```


## Load Libraries

```{r, echo = FALSE}
library(ggplot2)
library(pander)
library(tidyverse)
library(viridis)
```

## Define Standard Error Function:
```{r}
std <- function(x) sd(x)/sqrt(length(x))
```


## Meditation Analysis
```{r}
data <- "data/meditation.csv" %>%
  read_csv() %>%
  mutate_if(is.character,as.factor) %>%
  select(-c(average))


test <- data %>%
  pivot_longer(!initial_hr & !final_hr, names_to = "trial", values_to = "reaction_time")
  
(test)
  
df <- test %>%
  group_by(trial) %>%
  summarise(mean = ave(reaction_time), std = std(reaction_time)) %>%
  unique()-> out


ggplot(df, aes(x = trial , y = mean, fill= trial, label = paste0('\nAVG: ', round(mean, 3),"\n STD: ", round(std, 3), "\n"))) +
  geom_bar(position=position_dodge(), stat="identity")  +
  scale_fill_discrete("Trial", 
                      labels=c("Before Meditation", "After Meditation")) +
  geom_errorbar(aes(ymin=mean-std, ymax=mean+std, width=.5))  +
    geom_text(nudge_y = 0.05, size = 3) +
  # facet_wrap(~Force, drop = FALSE, strip.position = 'bottom') +
    xlab("Before and After Meditation") + ylab("Average Reaction Time (s)")  +
   theme( axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```


# Two tailed paired ttest for meditation reaciton time
```{r}
(data)

res <- t.test(data$initial_rt, data$final_rt, paired = TRUE, alternative = 'greater')
pander(res)
```



## Exercise Analysis
```{r}

data <- "data/exercise.csv" %>%
  read_csv() %>%
  mutate_if(is.character,as.factor) %>%
  select(-c(average))

test <- data %>%
  pivot_longer(!initial_hr & !final_hr, names_to = "trial", values_to = "reaction_time")
  
(test)
  
df <- test %>%
  group_by(trial) %>%
  summarise(mean = ave(reaction_time), std = std(reaction_time)) %>% unique()-> out


ggplot(df, aes(x = trial , y = mean, fill= trial, label = paste0('\nAVG: ', round(mean, 3),"\n STD: ", round(std, 3), "\n"))) +
  geom_bar(position=position_dodge(), stat="identity") +
  scale_fill_discrete("Trial", 
                      labels=c("Before Exercise", "After Exercise")) +
  geom_errorbar(aes(ymin=mean-std, ymax=mean+std, width=.5))  +
    geom_text(nudge_y = 0.05, size = 3) +
  # facet_wrap(~Force, drop = FALSE, strip.position = 'bottom') +
    xlab("Before and After Exercise") + ylab("Average Reaction Time (s)")  +
   theme( axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

## Two tailed Paired ttest for reaction time for exercise
```{r}
(data)
res <- t.test(data$initial_rt, data$final_rt, paired = TRUE, alternative = 'greater')
pander(res)
```


## Comparing groups

```{r}
ex <- "data/exercise.csv" %>%
  read_csv() %>%
  mutate_if(is.character, as.factor) %>%
  select(-c(average, initial_hr, final_hr)) %>%
  mutate( diff = abs(final_rt - initial_rt)) %>%
  mutate( group = 'exercise' ) %>%
  select(c(group, diff))

med <- "data/meditation.csv" %>%
  read_csv() %>%
  mutate_if(is.character,as.factor) %>%
  select(-c(average, initial_hr, final_hr)) %>%
  mutate( diff = abs(final_rt - initial_rt)) %>%
  mutate( group = 'mediation' ) %>%
  select(c(group, diff))

df <- ex %>%
  bind_rows(med) %>%
  group_by(group) %>%
  summarise(mean = ave(diff), std = std(diff)) %>%
  unique()-> out



ggplot(df, aes(x = group , y = mean, fill= group, label = paste0('\nAVG: ', round(mean, 3),"\n STD: ", round(std, 3), "\n"))) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=mean-std, ymax=mean+std, width=.5))  +
    geom_text(nudge_y = 0.012, size = 3) +
  # facet_wrap(~Force, drop = FALSE, strip.position = 'bottom') +
    xlab("Group") + ylab("Average Difference in Reaction Time (s)")  +
   theme( axis.text.x=element_blank(),
        axis.ticks.x=element_blank())


```



# Two tailed t test comparing reaction time
```{r}
res <- t.test(ex$diff, med$diff, paired = FALSE,  alternative = 'two.sided')
pander(res)
```




## Meditation Analysis
```{r}
data <- "data/meditation.csv" %>%
  read_csv() %>%
  mutate_if(is.character,as.factor) %>%
  select(-c(average))


test <- data %>%
  pivot_longer(!initial_rt & !final_rt, names_to = "trial", values_to = "heart_beat") %>% 
  .[-c(1,2),] %>%
  mutate(heart_beat = as.character(heart_beat)) %>% mutate(heart_beat = as.numeric(heart_beat))
  
(test)
  
df <- test %>%
  group_by(trial) %>%
  summarise(mean = ave(heart_beat), std = std(heart_beat)) %>%
  unique()-> out


ggplot(df, aes(x = trial , y = mean, fill= trial, label = paste0('\nAVG: ', round(mean, 3),"\n STD: ", round(std, 3), "\n"))) +
  geom_bar(position=position_dodge(), stat="identity")  +
  scale_fill_discrete("Trial", 
                      labels=c("Before Meditation", "After Meditation")) +
  geom_errorbar(aes(ymin=mean-std, ymax=mean+std, width=.5))  +
    geom_text(nudge_y = 0.05, size = 3) +
  # facet_wrap(~Force, drop = FALSE, strip.position = 'bottom') +
    xlab("Before and After Meditation") + ylab("Average Reaction Time (s)")  +
   theme( axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```










